### ISSUE TITLE
Adding feature Dark Mode

### ISSUE THREAD

**Issue by Mahi-Awasthi** [Rtarun3606k/Walkez#58]
### Purpose
- [ ] Adding a new file
- [ ] Changing an existing file

### Affected Files
List the files that are being added or changed:
1. `path/to/file1`
2. `path/to/file2`

### Proposed Changes
Provide a brief description of the changes you are proposing:

### Screenshots (if applicable)
Please attach any screenshots that will help explain your changes:

**Comment by Rtarun3606k** [comment]
Hi @Mahi-Awasthi ,

I noticed that someone opened an issue in the GitHub repository requesting a dark mode feature, and I was considering assigning it to you. Before I do, I just wanted to check in and see if you're familiar with React and if you’re comfortable implementing the dark mode feature without causing any code conflicts.

Have you worked on any previous projects in React with dark mode? If so, it would be great to know about your experience with that. Let me know your thoughts !.  You can complete all of your four pull request for hacktober fest  

Thanks,
